<?php
require_once("functions/sql.php");
require_once("functions/notification.php");
require_once("functions/payment.php");
require_once("functions/general.php");
require_once("functions/cart.php");
require_once("functions/svg.php");
require_once("functions/system.php");
require_once("functions/vouchers.php");
require_once("functions/products.php");
require_once("functions/currency.php");
?>